### ISSUE TITLE
ltsgraph vector export seems to be broken

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1411]
*Issue migrated from trac ticket # 1410*

**component:** ltsgraph | **priority:** minor

#### 2017-05-23 14:38:16: aclopte@gmail.com created the issue

___
When exporting the image to any of the vector graphics formats (ps, eps, pdf, svg, tex) the output is a malformed file, only with svg there is a proper image, which does not look as it should either.

Should be easily reproducible, I have gl2ps version 1.3.9.

**Comment by mlaveaux** [comment]
We have decided to remove the generation of vector graphics from ltsgraph and ltsview using gl2ps because of the following reasons:
 
Most importantly, the generated vector graphics were unusable for any reasonable state spaces due to their size (3.5MB for a state space of 10 states) because OpenGL only deals with triangles. Furthermore, the amount of work required to make gl2ps work without feedback mode was too much for these results.

However, generating vector graphics can be useful and a features request #1465 has been opened to track progress.
