### ISSUE TITLE
atermpp::bottom_up_replace causes stack overflow when saving large PBESses

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1412]
*Issue migrated from trac ticket # 1411*

**component:** General | **priority:** major

#### 2017-05-29 11:22:02: @wiegerw created the issue

___
Some large PBESses with deeply nested conjunctions can not be saved if the stack size is too small. This is caused by atermpp::bottom_up_replace, that is implemented using a visitor framework.

Other algorithms fail as well. For example the PBES normalize function  also requires a large stack size.

**Comment by wiegerw** [comment]
A lot of code in the toolset uses recursion, I would not call this a bug.

**Comment by mlaveaux** [comment]
The saving issue should be resolved because we no longer use bottom_up_replace while saving PBESses in the new format. The remove index function is now applied while saving and the resulting terms are stored on the heap. For MacOS we have explicitly increased the reserved stack size at build time, and we could also consider doing this for Windows builds if necessary.
