### ISSUE TITLE
PBES pretty printer does not print parentheses on left-hand side of implication

### ISSUE THREAD

**Issue by tneele** [mCRL2org/mCRL2#1483]
The PBES pretty printer seems to be implemented with the assumption that the implication operator is left-associative. See the following specification:
```
pbes nu X1(c:Bool) = (X1(c) => val(c)) => val(c);

init X1(false);
```
Save this in a file `1.txt` and execute the following commands:
```
txt2pbes 1.txt 1.pbes && pbespp 1.pbes 2.txt && txt2pbes 2.txt 2.pbes && pbessolve 1.pbes && pbessolve 2.pbes
```
The resulting output is:
```
true
[error]   The PBES is not monotonic!
```
The file `2.txt` now contains the following:
```
pbes nu X1(c: Bool) =
       X1(c) => val(c) => val(c);

init X1(false);
```
The expression `X1(c) => val(c)` should be surrounded with parentheses.

**Comment by wiegerw** [comment]
The function `print_pbes_binary_operation` doesn't take left/right associativity of binary operators into account. It is based on the wrong assumption that operators are both left and right associative.

To fix this, traits functions should be added that determine if a binary operator is left or right associative. And the function `print_pbes_binary_operation` should get alternative cases based on the associativity of the operators.

This problem is most likely present in other libraries too. It seems a bit late to fix this for the release, since it requires extensive changes.

**Comment by wiegerw** [comment]
If the `print_binary_operation` functions are implemented in terms of the associativity of operators, all the clumsy `left_precedence` and `right_precedence` functions can be removed. These functions were derived from the original pretty print functionality in the toolset, which I never fully understood.
