### ISSUE TITLE
pbespgsolve computes wrong solution

### ISSUE THREAD

**Issue by tneele** [mCRL2org/mCRL2#1502]
The following PBES was generated during random tests:
```
pbes
mu X0 = (X1(1, 1)) && ((((val(false)) && (((val(false)) => (val(true))) || (val(true)))) || (!X0)) => (X2));
nu X1(n:Nat, m:Nat) = ((val(m == n)) || (!((val(false)) || (!(val(true)))))) => ((X3(m > 0, m + 1)) && ((X0) || ((val(n < 2)) && (X2))));
nu X2 = ((!(forall u:Nat.((val(u < 3)) && ((!((!((exists w:Nat.((val(w < 3)) || (val(w > 1)))) => (!X0))) && (X2))) || (!(val(false))))))) && (X1(1, 0))) && ((val(false)) => (val(false)));
mu X3(b:Bool, m:Nat) = ((!((exists w:Nat.((val(w < 3)) || (val(m == w)))) && (exists v:Nat.((val(v < 3)) || (val(v < 3)))))) => (forall u:Nat.((val(u < 3)) && (!(exists w:Nat.((val(w < 3)) || ((X1(0, 1)) || (X0)))))))) => (!(!(exists w:Nat.((val(w < 3)) || ((val(w > 0)) => ((val(m < 3)) => (X2)))))));

init X0;
```
When solving this PBES, pbespgsolve yields false for all algorithms, while pbessolve and pbes2bool yield true.
The following results were generated from the random test:
```
Output of pbespgsolve -srecursive: {'solution': False}
Output of pbespgsolve -sprioprom: {'solution': False}
Output of pbespgsolve -sspm: {'solution': False}
Output of pbespgsolve -saltspm: {'solution': False}
Output of pbes2bool : {'solution': True}
Output of pbespgsolve -c: {'solution': False}
```

**Comment by wiegerw** [comment]
Reopen the issue, since the random tests found a new instance.

{{{
pbes
mu X0 = (exists w:Nat.((val(w < 3)) || (forall t:Nat.((val(t < 3)) && (forall v:Nat.((val(v < 3)) && (val(t < 2)))))))) => ((((!(val(false))) || (val(true))) => (!X2)) => ((X1(1)) && ((val(false)) || (X0))));
mu X1(m:Nat) = ((!X1(1)) => (!(!X2))) && ((((val(m > 1)) && (val(true))) && (!X3(1, false))) => ((val(m > 1)) => (val(true))));
nu X2 = ((!X0) => ((val(false)) && (X2))) || ((val(false)) && (((exists t:Nat.((val(t < 3)) || (X1(1)))) => (!(val(true)))) => (exists t:Nat.((val(t < 3)) || (!(val(t > 1)))))));
mu X3(m:Nat, c:Bool) = (((val(true)) || (val(true))) && (((X0) || (val(m < 2))) || (X3(1, false)))) && ((forall u:Nat.((val(u < 3)) && (X2))) && (val(c)));

init X0;
}}}
