### ISSUE TITLE
pbesinst reverses value list on when instantiating multiple parameters at once

### ISSUE THREAD

**Issue by tneele** [mCRL2org/mCRL2#1516]
**Steps to reproduce**
Take the following PBES and save it in test.txt:
```
sort D = struct d1 | d2;
pbes nu Y(b:Bool,d:D) = Y(!b,d);
init Y(true,d1);
```
Execute the following commands:
```
txt2pbes test.txt test.pbes
pbesinst -sfinite --select="*(*:Bool,*:D)" test.pbes test.min.pbes
pbespp test.min.pbes
```
**Expected result**: the resulting PBES is well-formed.
**Actual result**: the resulting PBES contains predicate variable instatiations of the shape `Y@d1@true`, while all the variables bound in this PBES have the shape `Y@true@d1`.

**Comment by jgroote** [comment]
I am in favour of using Y_d1_true instead of Y@d1@true. Using unique name generators,
the name Y_d1_true may be provided with a postfix to guarantee their uniqueness. This should probably also be applied at other places. 

The workflow where the PBES is printed, @ are replaced using sed and the resulting PBES is parsed
is not a convenient one.

**Comment by tneele** [comment]
@jgroote Your comment seems to refer to issue #1508.
