### ISSUE TITLE
The conditional process operator may not parse when there are no parentheses around the condition

### ISSUE THREAD

**Issue by Valo13** [mCRL2org/mCRL2#1518]
The mCRL2 specification `init true == true -> tau;` does not parse and gives the following error:
```
[parser::error]   Line 1, column 10: syntax error after 'true'
[parser::error]     init true == true -> tau;
[parser::error]               ^
[parser::error]   Unexpected '=='
[error]   syntax error
```

Is it intended that this does not parse or should this parse correctly?
When there are parentheses put around the condition (`init (true == true) -> tau;`) it does parse correctly.

**Comment by wiegerw** [comment]
The mCRL2 language is not very parser friendly. Parsing the if/then/else syntax for process expressions was particularly hard due to all the possible ambiguities in the language. The current grammar is

```(DataExprUnit '->' $unary_op_right 5) ProcExpr```

where DataExprUnit allows to omit parentheses for a limited set of data expressions. Given the huge effort it has already taken to get this working I don't think it will be changed.

**Comment by jgroote** [comment]
mCRL2 insisted on having brackets around non trivial conditions since the beginning.
It is intended that the parser is not able to parse your example, in order to avoid more complex parsing 
problems. 

Regards, Jan Friso 

> On 6 Feb 2019, at 16:17, Olav Bunte <notifications@github.com> wrote:
> 
> The mCRL2 specification init true == true -> tau; does not parse and gives the following error:
> 
> [parser::error]   Line 1, column 10: syntax error after 'true'
> [parser::error]     init true == true -> tau;
> [parser::error]               ^
> [parser::error]   Unexpected '=='
> [error]   syntax error
> 
> Is it intended that this does not parse or should this parse correctly?
> When there are parentheses put around the condition (init (true == true) -> tau;) it does parse correctly.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

____________________________________________________________________________________
Jan Friso Groote, Eindhoven University of Technology, Department of Mathematics and
Computer Science, Metaforum room MF 6.079b, Groene Loper 5, 5612 AE Eindhoven. 
The Netherlands. +31-40-247 5003, secretary: +31-40-247 5145,
J.F.Groote@tue.nl, www.win.tue.nl/~jfg, Skype: janfriso
Home: Hoekstraat 56, 5674 NP Nederwetten, +31 40 2845414, +31 6 81922128

**Comment by Valo13** [comment]
As this issue was (for me) more about knowing the reason behind this and not about the desire to have this fixed, I'll close it.
