### ISSUE TITLE
Function rewriting and Bool type Expressions

### ISSUE THREAD

**Issue by matifch** [mCRL2org/mCRL2#1529]
an error occurred while calculating the transitions from this state;
Expression 1 < power(2, 2) && power(2, 2) < 20 does not rewrite to true or false in the condition 1 < a_P && a_P < 20

map
 power: Int#Int->Int;
var
 n,m:Int;
eqn
 power(n,0)=1;
 power(n, succ(m))=n*power(n,m);
act  
 aAction, bAction, cAction:Int;
proc 
P(a:Int, b:Int)= aAction(a).P(power(a,b),b);
P2(x:Int)=sum i:Int.(i>1&&i<20)->bAction(i).P2(x+i);

init 
 allow({cAction},
comm({aAction|bAction->cAction},

P(2,2)||P2(0)
));

**Comment by jgroote** [comment]
Hello Muhammad,

The problem in the specification below is that the rule:

  power(n,succ(m)) = n * power(n,m)

does not match on power(2,2) as 2 is internally written as something like @cDub(true,c0).
If you replace the rule above by

m>0 -> power(n,m) = n*power(n,m-1) 

it should work fine. This matching is something that I do not
particularly like to be honest, because it leads to mistakes that people
only understand if they know both what mathing is and understand
the internal structure.

Regards, Jan Friso 



> On 8 Apr 2019, at 19:53, matifch <notifications@github.com> wrote:
> 
> an error occurred while calculating the transitions from this state;
> Expression 1 < power(2, 2) && power(2, 2) < 20 does not rewrite to true or false in the condition 1 < a_P && a_P < 20
> 
> map
> power: Int#Int->Int;
> var
> n,m:Int;
> eqn
> power(n,0)=1;
> power(n, succ(m))=n*power(n,m);
> act
> aAction, bAction, cAction:Int;
> proc
> P(a:Int, b:Int)= aAction(a).P(power(a,b),b);
> P2(x:Int)=sum i:Int.(i>1&&i<20)->bAction(i).P2(x+i);
> 
> init
> allow({cAction},
> comm({aAction|bAction->cAction},
> 
> P(2,2)||P2(0)
> ));
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

____________________________________________________________________________________
Jan Friso Groote, Eindhoven University of Technology, Department of Mathematics and
Computer Science, Metaforum room MF 6.079b, Groene Loper 5, 5612 AE Eindhoven. 
The Netherlands. +31-40-247 5003, secretary: +31-40-247 5145,
J.F.Groote@tue.nl, www.win.tue.nl/~jfg, Skype: janfriso
Home: Hoekstraat 56, 5674 NP Nederwetten, +31 40 2845414, +31 6 81922128
