### ISSUE TITLE
Quantifier in equations

### ISSUE THREAD

**Issue by matifch** [mCRL2org/mCRL2#1533]
I have a question about the following function which is not working and I want to know the reason and make it working. 

map
    isSorted: List(Int)->Bool;
var
    lst:List(Int);
eqn
isSorted(lst)=forall j:Nat.lst.j<=lst.(j+1);

I have also tried 
isSorted(lst)=forall j:Nat.lst.j<=lst.(j+1) whr j<#lst end;

but unfortunately it is violating syntax. 

Moreover, can someone send me equations for sorting a list?

**Comment by jkeiren** [comment]
In mCRL2 the set of natural numbers is, like its mathematical counterpart, countably infinite. Therefore, your first equation tries to unfold all natural numbers.

Your second approach with the where-clause does not work, since the where clause is simply a shorthand for a beta redex.

Without having tried it myself, I would suggest to try something like:
isSorted(lst) = forall j: Nat . (j < #lst-1) => (lst.j <= lst.(j+1));

**Comment by Valo13** [comment]
This can also be done recursively without using quantifiers, which I expect to be more efficient, with something like:
`isSorted(lst) = if(#lst < 2, true, head(lst) <= head(tail(lst)) && isSorted(tail(lst)));`
I have not checked this for correctness though

**Comment by jkeiren** [comment]
In @Valo13 's proposal, you could actually use a where clause that might improve performance:
`isSorted(lst) = if(#lst < 2, true, head(lst) <= head(t) && isSorted(t)) where t = tail(lst);`
This solution looks correct to me, and is likely to be much faster than the earlier proposal.

**Comment by Valo13** [comment]
@jkeiren 
Syntactically correct that would be
`isSorted(lst) = if(#lst < 2, true, head(lst) <= head(t) && isSorted(t) whr t = tail(lst) end);`
