### ISSUE TITLE
Default Behaviour of a  Lambda term

### ISSUE THREAD

**Issue by matifch** [mCRL2org/mCRL2#1534]
In the following example, "square" function is specified but as special cases, it gives output 1 if input is 0 and likewise gives 2 if input is 1 (written as [0->1][1->2]). 
My question is how may I give three inputs as a special case to the function "divide", given below?
My interest to make a special cases when any of the input is 0. 
 something like  [(0,b,bl)->0] [(a,0,bl)->0] I tried but in vain. 

map square:Nat->Nat;
divide:Nat#Nat->Real;
var n:Nat;
    a,b:Nat;
   bl:Bool;
eqn square(n)=(lambda z:Nat.(z*z))[0->1] [1->2] (n);
divide(a,b)=(lambda x,y:Nat,z:Bool.if(z, a/b, b/a))(a,b, a>b);

**Comment by jgroote** [comment]
Hello Muhammad,

I think you want to write:

> eqn square(n)=(lambda z:Nat.(z*z))[0->1][1->2](n);

namely apply the updated function to an argument, as otherwise it does not have type nat. 
Hope this helps. I had to look for a few minutes to the example before I saw the problem.

I still have to look to your mail. I am currently in Beijing, China and planning to answer your other
mail shortly.

Regards, Jan Friso 

> On 25 May 2019, at 16:08, matifch <notifications@github.com> wrote:
> 
> In the following example, "square" function is specified but as special cases, it gives output 1 if input is 0 and likewise gives 2 if input is 1 (written as [0->1][1->2]).
> My question is how may I give three inputs as a special case to the function "divide", given below?
> My interest to make a special cases when any of the input is 0.
> something like [(0,b,bl)->0] [(a,0,bl)->0] I tried but in vain.
> 
> map square:Nat->Nat;
> divide:Nat#Nat->Real;
> var n:Nat;
> a,b:Nat;
> bl:Bool;
> eqn square(n)=(lambda z:Nat.(z*z))[0->1]1->2;
> divide(a,b)=(lambda x,y:Nat,z:Bool.if(z, a/b, b/a))(a,b, a>b);
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

____________________________________________________________________________________
Jan Friso Groote, Eindhoven University of Technology, Department of Mathematics and
Computer Science, Metaforum room MF 6.079b, Groene Loper 5, 5612 AE Eindhoven. 
The Netherlands. +31-40-247 5003, secretary: +31-40-247 5145,
J.F.Groote@tue.nl, www.win.tue.nl/~jfg, Skype: janfriso
Home: Hoekstraat 56, 5674 NP Nederwetten, +31 40 2845414, +31 6 81922128

**Comment by tneele** [comment]
mCRL2 currently does not support function updates for functions with more than one parameter. See issue #894. The best alternative for this specific case is to use pattern matching in rewrite rules, like this:
```
map 
  divide: Nat # Nat -> Real;
var
  a,b: Nat;
eqn
  divide(0,b) = 0;
  divide(a,0) = 0;
  divide(a,b) = if(a > b, a/b, b/a);
```

**Comment by matifch** [comment]
Thanks Thomas, 
I was looking the same you pointed out, i.e., using more than one parameters as default mapping. 

regards,
Muhammad Atif.
