### ISSUE TITLE
lps2lts can not rewrite stochastic operator in the initial state

### ISSUE THREAD

**Issue by wiegerw** [mCRL2org/mCRL2#1542]
When applying the commands

```
txt2lps 3.mcrl2 3.lps
lps2lts -Q0 3.lps 3.aut
```

to the specification

```
proc P = delta;

init dist b: Bool[if(b, 1 / 4, 3 / 4)] . P;
```
an error is reported: `[error]   Comparison of fraction does not rewrite to true or false: 0 < if(b, 1 / 4, 3 / 4).`. Without the option `-Q0` it succeeds. Something goes wrong during enumeration of the distribution.

**Comment by tneele** [comment]
I looked into this issue, and the problems is as follows. The help text of the `-Q` option specifies that:

> limit enumeration of quantifiers to NUM variables. (Default NUM=1000, NUM=0 for unlimited).

However, this is not at all consistent with the implementation. First of all, the value 0 is not a special value, so the commandline option `-Q0` implies that no enumeration takes place at all. Secondly, the value NUM that the user supplied is not used to limit the number of variables, but the number of iterations of the enumerator. The value is first stored in a static variable via the function `set_enumerator_variable_limit`, but ends up in the class attribute `m_max_count` of `enumerator_algorithm`, which limits the number of iterations, instead of the number of variables.

I propose the following changes:

- Change `mcrl2/data/rewriter_tool.h` to give `NUM=0` the special value of unlimited enumeration (or at least `std::numeric_limits<std::size_t>::max`).
- Update the description of the `--qlimit` option and the `set_enumerator_variable_limit` to reflect that they limit the number of enumerator iterations.

@jgroote Do you agree with these changes?

**Comment by jgroote** [comment]
Agreed.

Jan Friso Groote
www.win.tue.nl/~jfg<http://www.win.tue.nl/~jfg>

On 29 Jul 2019, at 12:57, Thomas Neele <notifications@github.com<mailto:notifications@github.com>> wrote:


I looked into this issue, and the problems is as follows. The help text of the -Q option specifies that:

limit enumeration of quantifiers to NUM variables. (Default NUM=1000, NUM=0 for unlimited).

However, this is not at all consistent with the implementation. First of all, the value 0 is not a special value, so the commandline option -Q0 implies that no enumeration takes place at all. Secondly, the value NUM that the user supplied is not used to limit the number of variables, but the number of iterations of the enumerator. The value is first stored in a static variable via the function set_enumerator_variable_limit, but ends up in the class attribute m_max_count of enumerator_algorithm, which limits the number of iterations, instead of the number of variables.

I propose the following changes:

  *   Change mcrl2/data/rewriter_tool.h to give NUM=0 the special value of unlimited enumeration (or at least std::numeric_limits<std::size_t>::max).
  *   Update the description of the --qlimit option and the set_enumerator_variable_limit to reflect that they limit the number of enumerator iterations.

@jgroote<https://github.com/jgroote> Do you agree with these changes?
