### ISSUE TITLE
Quatifiers with Modal Formula having more than one action

### ISSUE THREAD

**Issue by matifch** [mCRL2org/mCRL2#1596]
I want to use quantifiers with a modal mu-calculus formula. 
```
forall d:weekDays.[true*.transferDay(d)] mu X.[!forwardDay(nextDay(d))]X 
```
where `transferDay` and `forwardday` are two actions of type `weekDays` while `nextDay` is a function to provide next element in a user defined data type
```
weekDays= struct Monday|Tuesday|Wedensday|Thursday|Friday|
                   Saturday|Sunday;  
```
According to Jan Friso's book quantifiers are used with a single action formula. So, I am curious to know how can we verify a requirement where there are more than one actions. 
The above formula is true and it is also supposed to be true but the following formula is also true according to toolset but indeed it should not be w.r.t. the following specifications.
```
forall d:weekDays.[true*.transferDay(d)] mu X.[!forwardDay(d)]X
```
I am experimenting on the following example:
```
sort
  weekDays= struct Monday|Tuesday|Wedensday|Thursday|Friday|
                   Saturday|Sunday;
 map
  nextDay:weekDays->weekDays;
 var
  d:weekDays;
 eqn
  (d==Monday)   ->nextDay(d)=Tuesday;
  (d==Tuesday)  ->nextDay(d)=Wedensday;
  (d==Wedensday)->nextDay(d)=Thursday;
  (d==Thursday) ->nextDay(d)=Friday;
  (d==Friday)   ->nextDay(d)=Saturday;
  (d==Saturday) ->nextDay(d)=Sunday;
  (d==Sunday)   ->nextDay(d)=Monday;
 act
  sendDay,rcvDay,transferDay:weekDays;
  forwardDay:weekDays;
 proc
  Sender=sum d:weekDays.sendDay (d).delta;
  Receiver=sum d1:weekDays. rcvDay(d1).forwardDay(nextDay(d1)).delta;
 init
  allow({transferDay,forwardDay},
  comm({sendDay|rcvDay->transferDay},
        Sender||Receiver ));
```

**Comment by tneele** [comment]
I observe the same behaviour as you: the toolset reports that both properties hold for this specification. I think this matches with the semantics outlined in the book. Let us consider the following simplified version of the second property, where we only consider Monday:
```
[true*.transferDay(Monday)] mu X.[!forwardDay(Monday)]X
```
After the action `transferDay(Monday)` occurs, we are obligated to satisfy the formula `mu X.[!forwardDay(Monday)]X`. At that point in the LTS, we can only perform the action `forwardDay(Tuesday)`, after which we end up in a deadlock. This satisfies `mu X.[!forwardDay(Monday)]X`, since all traces not containing `forwardDay(Monday)` are indeed finite. I think the formula you are actually looking for is
```
forall d:weekDays.[true*.transferDay(d)] mu X.([!forwardDay(d)]X && <true> true)
```
Now we require that all traces not containing `forwardDay(d)` are finite, and no deadlock occurs in the meantime, i.e., `forwardDay(d)` happens unavoidably. This formula is false, according to the toolset.

Does this answer your question?

**Comment by matifch** [comment]
Absolutely Yes. So kind of Thomas Neele for the detailed reply.
