### ISSUE TITLE
Jittyc is very slow in case of many nested struct updates

### ISSUE THREAD

**Issue by Valo13** [mCRL2org/mCRL2#1609]
See example [bigupdate_spec.txt](https://github.com/mCRL2org/mCRL2/files/4836801/bigupdate_spec.txt).

This example is generated from a simple OIL specification with two transitions:
 - A transition of event `bigupdate_i_u_call_reactive` that assigns `false` to a boolean `b` fifty times.
 - A transition of event `bigupdate_i_e_call_reactive` that increments a counter `n` if `n < 10`.

These result in two summands as can be seen in the supplied mcrl2 file (which has extension `.txt` since github does not seem to allow `.mcrl2` files).
The summand of event `bigupdate_i_u_call_reactive` contains 50 equality checks, one for each assignment, that check whether the assignments were applied successfully, that is boolean `b` has value `false` after applying all assignments (for those who were at my last colloquium presentation, these are compatibility checks).

After generating the LPS from this using `mcrl22lps bigupdate_spec.mcrl2 bigupdate.lps`, one can create the LTS using `lps2lts bigupdate.lps bigupdate.lts` within a second. However, when using the option `-rjittyc` for `lps2lts` it seems to get stuck after having compiled the rewriter. Using option `-v` shows that it gets stuck before showing the progress of the state space generation.

Experiments show the following:
 - The summand of event `bigupdate_i_e_call_reactive` seems to be necessary.
 - The fact that all assignments on the transition of event `bigupdate_i_u_call_reactive` are the same does not matter, I have made them the same to reduce the size of the specification.

This was tested on on a virtual machine with Ubuntu 20.04 using version 201908.0.52c2b30918 (Release) of the mCRL2 tool set.

**Comment by tneele** [comment]
Since I'm not very knowledge about the match trees in jittyc, I'm just posting my conclusions as I go. The problem can conveniently be reproduced in the `mcrl2i` REPL. Here, `a.lps` contains the specification posted by @Valo13.
```
> mcrl2i a.lps
? r jittyc
? e SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(SET_b(OIL_GS_struct(false,0), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false), true, false)
```

For the `SET_b` function, the following code is generated by jittyc:

```c
// [30] SET_b: OIL_GS_type # Bool # Bool -> OIL_GS_type
template < class DATA_EXPR0, class DATA_EXPR1, class DATA_EXPR2>
static inline data_expression rewr_30_3(const DATA_EXPR0& arg_not_nf0, const DATA_EXPR1& arg_not_nf1, const DATA_EXPR2& arg_not_nf2, RewriterCompilingJitty* this_rewriter)

{
  // @@A(1)
  const data_expression& arg1 = local_rewrite(arg_not_nf1,this_rewriter);
  // Considering argument 1
  // @@S(@var_0, @@N(@@F(false, @@D(@@N(@@R(@var_0))), @@X)))
  {
    const data_expression& var_0 = local_rewrite(arg_not_nf0, this_rewriter); // S1
    if (uint_address(arg1) == 0x6c0200) // F1
    {
      return var_0; // R1 @var_0
    }
    else
    {
    }
  }
  // @@A(0)
  const data_expression& arg0 = local_rewrite(arg_not_nf0,this_rewriter);
  // Considering argument 0
  // @@F(OIL_GS_struct, @@N(@@S(@var_1, @@D(@@N(@@F(true, @@D(@@N(@@S(@var_2, @@R(OIL_GS_struct(@var_2, @var_1))))), @@X))))), @@X)
  {
    if (uint_address((is_function_symbol(arg0) ? arg0 : arg0[0])) == 0x6c1df0) // F1
    {
      const data_expression& var_1 = down_cast<data_expression>(arg0[2]); // S2
      if (uint_address(arg1) == 0x6c01d0) // F1
      {
        const data_expression& var_2 = local_rewrite(arg_not_nf2, this_rewriter); // S1
        return rewr_32_2(var_2, var_1,  this_rewriter); // R1 OIL_GS_struct(@var_2, @var_1)
      }
      else
      {
      }
    }
    else
    {
    }
  }
  return application(atermpp::down_cast<data_expression>(atermpp::aterm(reinterpret_cast<atermpp::detail::_aterm*>(0x6c1ca0))), arg0, arg1, local_rewrite(arg_not_nf2,this_rewriter));
}
```
Call graphs show that this is the source of an exponential complexity, since the function call `local_rewrite(arg_not_nf0, this_rewriter)` happens twice.

**Comment by tneele** [comment]
After discussion with @mlaveaux, the conclusion is that just-in-time only works from left to right in jittyc. In this case, the second argument is matched first, and the first argument is rewritten twice in every recursive step. So, @Valo13, a workaround for you is to swap the first two arguments of the `SET_n` function.

**Comment by mlaveaux** [comment]
I suspected the left-to-right limitation at first. However, it is the case that the first two arguments are both necessary. Namely, the first argument occurs in the right-hand side of the first rewrite rule and its head symbol is inspected in the second case. 

For the jitty implementation the normal form of the rewritten arguments are stored in an array that is used while matching. 

The generated match tree does not recall the normal form of the first argument, which is computed for the substitution of var_0 (variable v_OIL_GS), and instead performs normalisation again for A(0). I am not too familiar with the just-in-time extension of match trees, but this seems to be a limitation of match trees as they also operate on the arguments left-to-right. However, I do not understand why the match tree starts with A(1) instead of A(0), because the latter case it might actually avoid this problem because the implementation of S(x, ...) checks whether x is in normal form already if I understand the use of the m_used array correctly.

**Comment by jgroote** [comment]
I now looked at the analysis of Thomas. There are two odd aspects. Namely that the second argument of SET_b is rewritten
before the first argument is rewritten. But more worrying is that the first argument is rewritten twice. I consider this a bug
in the compiling rewriter, that requires further investigation. 

> On 26 Jun 2020, at 21:12, Maurice Laveaux <notifications@github.com> wrote:
> 
> 
> I suspected the left-to-right limitation at first. However, it is the case that the first two arguments are both necessary. Namely, the first argument occurs in the right-hand side of the first rewrite rule and its head symbol is inspected in the second case.
> 
> For the jitty implementation the normal form of the rewritten arguments are stored in an array that is used while matching.
> 
> The generated match tree does not recall the normal form of the first argument, which is computed for the substitution of var_0 (variable v_OIL_GS), and instead performs normalisation again for A(0). I am not too familiar with the just-in-time extension of match trees, but this seems to be a limitation of match trees as they also operate on the arguments left-to-right. However, I do not understand why the match tree starts with A(1) instead of A(0), because the latter case it might actually avoid this problem because the implementation of S(x, ...) checks whether x is in normal form already if I understand the use of the m_used array correctly.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

------------------------------------------------------------------------------------------------------------------------
Jan Friso Groote, Eindhoven University of Technology, Department of Mathematics and
Computer Science, Metaforum room MF 6.079b, Groene Loper 5, 5612 AE Eindhoven. 
The Netherlands. +31-40-247 5003, secretary: +31-40-247 5145,
J.F.Groote@tue.nl, www.win.tue.nl/~jfg, Skype: janfriso
Home: Hoekstraat 56, 5674 NP Nederwetten, +31 40 2845414, +31 6 81922128

**Comment by mlaveaux** [comment]
After looking at the relevant code in jittyc.cpp it is the case that the argument with the highest number of rules that depend on it is chosen first. The second argument has two dependencies and the first argument only one, because right-hand side dependencies are not considered in this calculation. When I adapted this ordering to always consider the arguments left-to-right the problem is avoided, because the implementation of S(var_0, ...) just assigns the already rewritten argument arg_0 to variable var_0. However, this might have other unintended side effects.

**Comment by jgroote** [comment]
The previous commit should have solved the problem. 
It also describes the nature of the issue.
