### ISSUE TITLE
parse and automatic save property modification in mcrl2ide

### ISSUE THREAD

**Issue by yuting1012** [mCRL2org/mCRL2#1612]
In the mcrl2ide property editing window, the "Parse" button check if the formula is well-formed without overwriting the original property file. Saving must be done explicitly and separately by pressing the"Save" button.

It happened to me several times that I parsed the file but forgot to save before closing the editing window, and my modifications were lost. Sometimes I didn't realize the problem till the long verification process returns a false.

I'd propose to have "Parse" do both **parsing and saving** in one go.

**Comment by matifch** [comment]
Moreover, upon parsing we get "the entered mu-calculus formula is valid" whereas we consider a formula valid if it holds. So, a suggestion is to change the message as, "the entered mu-calculus formula is well-formed"

**Comment by tneele** [comment]
Perhaps it's an idea to replace the three buttons `parse`, `save` and `cancel` by `parse & save`, `save` and `cancel`. An alternative is to show a warning message when clicking `cancel` would lead to a loss of unsaved changes. What do you think @Valo13?

> Moreover, upon parsing we get "the entered mu-calculus formula is valid" whereas we consider a formula valid if it holds. So, a suggestion is to change the message as, "the entered mu-calculus formula is well-formed"

This has already been resolved in #1558.

**Comment by yuting1012** [comment]
> Perhaps it's an idea to replace the three buttons `parse`, `save` and `cancel` by `parse & save`, `save` and `cancel`. An alternative is to show a warning message when clicking `cancel` would lead to a loss of unsaved changes. What do you think @Valo13?
> 

Or just add a warning message when closing the modified property without pressing any of these buttons

**Comment by tneele** [comment]
Ah, right, the close button in the title bar (or the escape key) has the same effect as the cancel button, while being less explicit about the consequences of clicking it.

**Comment by Valo13** [comment]
I'm not sure which of the two options is better. I'll just dump my thoughts here.

To save when parsing makes sense; the same happens when parsing the specification. However, the "Save" button closes the window which creates an expectation that the "Parse and Save" button does the same, but I see that as undesirable. This could be fixed by renaming the "Save" button to "Save and Close".
Also the "Parse and Save" button rises the question: do you still want to save when the property cannot be parsed? I'm inclined to answer this with yes (as this also happens with the specification).
It would probably make more sense to call the button "Save and Parse" as that is the order I would envision it to happen.

Using a warning message is consistent with the editor for specifications: whenever you exit while there are changes, you are notified of this. This would also cover the case where one edits the property and then closes the property window without parsing or saving.

I feel like the combination of the two would be the best solution here, where the first covers the case when parsing and the second covers the case when cancelling.
