### ISSUE TITLE
Release 201909 missing from historic releases on website

### ISSUE THREAD

**Issue by jkeiren** [mCRL2org/mCRL2#1617]
On [https://www.mcrl2.org/web/user_manual/historic_releases.html#historic-releases](https://www.mcrl2.org/web/user_manual/historic_releases.html#historic-releases), the previous mCRL2 release is missing. The newest release listed on that webpage is 201808.0.

The release from 2019 should be added as well.

Note that also on [https://www.mcrl2.org/web/user_manual/download.html](https://www.mcrl2.org/web/user_manual/download.html) the downloads of, e.g., the windows installer are not working (the links are dead).

**Comment by tneele** [comment]
The problem with the historic releases page is a known issue. I updated the source of that page, but the website is not being updated, since one `pbesbddsolve` random test keeps failing. @wiegerw Can you look into this?

I was not aware of the other issue with the regular download page, and I can also not reproduce it. Which link is dead exactly?

**Comment by Valo13** [comment]
The links for the windows installer work fine for me

**Comment by jkeiren** [comment]
The 2020 release is strange. Using Safari, if I click the links for the windows installer (.exe) or the DMG, I get a Not Found error. However, if from the resulting error page I force reload the download starts. The issue does not appear for the other file types. From Firefox this works fine. So I suppose the issue with the release page could be ignored for now.

**Comment by wiegerw** [comment]
Why does a failing random test prevent the update of a web page?

**Comment by tneele** [comment]
I think there are two reasons for this. Firstly, it seems undesirable to update the webpage with a broken nightly build. Secondly, as far as I know, the configuration in Teamcity forces an 'all or nothing' strategy, since it's not possible to distinguish between a failing test and a broken build. It would require quite some trickery to update only the webpages but not the nightly builds (if at all possible).

**Comment by jgroote** [comment]
The current strategy where any problem with building and testing the toolset prevents a probably problematic build to be uploaded is one that I like, as it makes it hard to ignore failing tests. If we do so, they can easily accumulate and linger around for years, as do some enhancement or bug requests. This will also lead to the situation that failing tests that indicate a serious problem, can easily be overlooked and ignored.

Of course requiring that tests should succeed, should not prevent to make tests, as the tests are extremely effective in catching many problems.

**Comment by wiegerw** [comment]
The current strategy does have the effect that I will be more conservative with adding tests.

**Comment by Valo13** [comment]
Maybe we can be less strict when it comes to tests that fail for non-release tools, since these are typically not used by users anyway and since (I feel like) tests for such tools are typically the ones that fail as these tools are still being worked on.
Then we could only not update the site etc if the build fails or if a test on a release tool fails.
I am not sure whether this is possible in TeamCity though (following @tneele's 'all or nothing' remark).

**Comment by tneele** [comment]
The website has been updated and the 201909.0 release is available again.
