### ISSUE TITLE
Problem with ltsgraph over Ubuntu

### ISSUE THREAD

**Issue by matifch** [mCRL2org/mCRL2#1623]
I am using mCRL2 toolset 202006.0 (Release) over Ubuntu 20.04.1 LTS where ltsgraph is giving the following error while ltsview is working fine
```
QOpenGLShader::compile(Vertex): 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES

*** Problematic Vertex shader source code ***
#version 330
#define lowp
#define mediump
#define highp
#line 1
uniform mat4 g_worldViewProjMatrix;
layout(location = 0) in vec3 vertex;
void main(void)
{
   gl_Position = g_worldViewProjMatrix * vec4(vertex, 1.0f);
}
***
[error]   0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES
Aborted (core dumped)
```

**Comment by mlaveaux** [comment]
The error message seems to indicate that the required opengl version, which is the graphics api that is used to present the graphics, is not available. The minimum required version has been opengl 3.3 since the 201908.0 release. It seems that ltsgraph does not actually check this minimum version, so that is something that we should improve. 

This minimum version should be widely available so perhaps the issue lies somewhere else. It might help to show the output of `ltsgraph -v` to see which opengl version is actually being used. Furthermore, the output of `glxinfo -B` can be used to identify the opengl version available on the system. The `glxinfo` tool seems to be part of the `mesa-utils` package on ubuntu.

**Comment by mlaveaux** [comment]
I have added a check in ltsgraph for the minimum required OpenGL version and an error is printed whenever this version is not present. Feel free to reopen this issue if this does not work as expected or you need further assistance.
