### ISSUE TITLE
Dividing by 0 does not produce any warnings

### ISSUE THREAD

**Issue by markuzzz** [mCRL2org/mCRL2#1631]
An expression like 1/0 == 2/0 will result in an error, it can not be rewritten to true or false. However 1/0 == 1/0 simply yields true. 
Minimal example:
act
	a;
init
	allow({a},(1/0 == 1/0) -> a.delta);

I understand why this happens but it feels akward. 1/0 is only sytanctically equal to 1/0, not semantically.

**Comment by jgroote** [comment]
The semantics of the data types says that syntactically equal objects are always semantically equal. That means
1/0 == 1/0. In the same way tail([]) = tail([]), although the models do not tell what the tail of an empty list is.
Syntactically different expressions may or may not be equal. As it is not defined what 1/0 and 2/0 are, there are
models where they are equal, and where they are not equal. Hence, 1/0 == 2/0 should not rewrite to true or false,
because there is not one way to do it. So, the behaviour is exactly in accordance with the semantics, and expectation.
