### ISSUE TITLE
Incompatibility with cmake-3.19.1

### ISSUE THREAD

**Issue by rmcgibbo** [mCRL2org/mCRL2#1634]
FYI: In https://github.com/NixOS/nixpkgs/pull/107441, it looks to me like the latest release fails to compile on Linux with cmake 3.19.1. I think this is due to [this regression](https://gitlab.kitware.com/cmake/cmake/-/issues/21500) in cmake itself. I'm not sure if this is actionable or not for you, but I figured I'd post a quick heads up.

**Comment by mlaveaux** [comment]
The issue that you have linked was indeed the reason why our toolset fails to configure with cmake 3.19.1. We set the variable 'CXX' in our cmake scripts at one point and that caused the observed error. I have fixed the issue, but that won't help for the released version. The fix was relatively straightforward so we could decide to add it to the mcrl2-202006.0 release. It seems that cmake 3.19.2 fixed the issue on their end and I was able to configure a build using that version without the fix.
