### ISSUE TITLE
mcrl2ide on Ubuntu

### ISSUE THREAD

**Issue by matifch** [mCRL2org/mCRL2#1638]
Upon every click on "Open" and "New project" icons, the following message appears on the terminal window:

08:35:19.206: GtkDialog mapped without a transient parent. This is discouraged.

 I am using mCRL2 toolset 202006.0 (Release) over
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

Moreover, after installing the above mcrl2, the output of
dpkg -l mcrl2
is not very clear, i.e.,:

Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  mcrl2          202006.0-1ub amd64        formal specification language too

**Comment by tneele** [comment]
The warning message seems to be a bug in Qt according to [this](https://stackoverflow.com/questions/47847739/qfiledialog-gtkdialog-mapped-without-a-transient-parent) StackOverflow question, so it's not anything we can solve.

> the output of `dpkg -l mcrl2` is not clear.

I guess you are referring to the package description, which is missing some part. The full description of the mcrl2 package in the Debian/Ubuntu repositories is 'formal specification language toolset'. I think the text is just cut off in your case because of the size of the command window.
