### ISSUE TITLE
lpsxsim for mac

### ISSUE THREAD

**Issue by matifch** [mCRL2org/mCRL2#1642]
The "enter" key doesn't work to execute some action in lpsxsim over macOS whereas the same key works fine for other operating systems (tested on Ubuntu and Windows).
I m using toolset 202006.0 (Release) upon macOS Big Sur version 11.2.3.
The keys "Backspace" and arrows work perfectly by the way.

**Comment by FerryT** [comment]
After some investigation it turns out this is a platform specific thing in Qt.
Items can be selected using the 'activation' key which is set to Enter in X11 and Windows, but for MacOS this is set to `⌘+O`.
Pressing this keyboard shortcut instead should have the intended effect.

**Comment by jgroote** [comment]
I just tested this. apple-O is assigned to open file in the menu.
It will not select anything.

------------------------------------------------------------------------------------------------------------------------
Jan Friso Groote, Eindhoven University of Technology, Department of Mathematics and
Computer Science, Metaforum room MF 6.079b, Groene Loper 5, 5612 AE Eindhoven.
The Netherlands. +31-40-247 5003, secretary: +31-40-247 5145,
***@***.******@***.***>, www.win.tue.nl/~jfg<http://www.win.tue.nl/~jfg>, Skype: janfriso
Home: Hoekstraat 56, 5674 NP Nederwetten, +31 40 2845414, +31 6 81922128



From: Ferry Timmers ***@***.***>
Date: Friday, 21 May 2021 at 14:34
To: mCRL2org/mCRL2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [mCRL2org/mCRL2] lpsxsim for mac (#1642)

After some investigation it turns out this is a platform specific thing in Qt.
Items can be selected using the 'activation' key which is set to Enter in X11 and Windows, but for MacOS this is set to ⌘+O.
Pressing this keyboard shortcut instead should have the intended effect.

**Comment by FerryT** [comment]
This also is the case when one of the transition options is highlighted, and the transition table has active focus?

**Comment by jgroote** [comment]
Yes. I can imagine that for a mac a separate option is added
to enable the enter/return key to select an item.

Jan Friso

------------------------------------------------------------------------------------------------------------------------
Jan Friso Groote, Eindhoven University of Technology, Department of Mathematics and
Computer Science, Metaforum room MF 6.079b, Groene Loper 5, 5612 AE Eindhoven.
The Netherlands. +31-40-247 5003, secretary: +31-40-247 5145,
***@***.******@***.***>, www.win.tue.nl/~jfg<http://www.win.tue.nl/~jfg>, Skype: janfriso
Home: Hoekstraat 56, 5674 NP Nederwetten, +31 40 2845414, +31 6 81922128



From: Ferry Timmers ***@***.***>
Date: Friday, 21 May 2021 at 14:47
To: mCRL2org/mCRL2 ***@***.***>
Cc: Groote, Jan Friso <j.f.groote@TUE.nl>, Comment ***@***.***>
Subject: Re: [mCRL2org/mCRL2] lpsxsim for mac (#1642)

This also is the case when one of the transition options is highlighted, and the transition table has active focus?

**Comment by FerryT** [comment]
Well, if this is not common MacOS behavior, then Qt's implementation is not very intuitive. I can override this, and set it to respond to the `Enter` and `Return` key for MacOS as well.

**Comment by jgroote** [comment]
Probably your last proposal is a good idea.

------------------------------------------------------------------------------------------------------------------------
Jan Friso Groote, Eindhoven University of Technology, Department of Mathematics and
Computer Science, Metaforum room MF 6.079b, Groene Loper 5, 5612 AE Eindhoven.
The Netherlands. +31-40-247 5003, secretary: +31-40-247 5145,
***@***.******@***.***>, www.win.tue.nl/~jfg<http://www.win.tue.nl/~jfg>, Skype: janfriso
Home: Hoekstraat 56, 5674 NP Nederwetten, +31 40 2845414, +31 6 81922128



From: Ferry Timmers ***@***.***>
Date: Friday, 21 May 2021 at 15:20
To: mCRL2org/mCRL2 ***@***.***>
Cc: Groote, Jan Friso <j.f.groote@TUE.nl>, Comment ***@***.***>
Subject: Re: [mCRL2org/mCRL2] lpsxsim for mac (#1642)

Well, if this is not common MacOS behavior, then Qt's implementation is not very intuitive. I can override this, and set it to respond to the Enter and Return key for MacOS as well.

**Comment by FerryT** [comment]
Overriding the behavior would be quite involved unfortunately.
I have reported this issue to Qt's bug tracker and hope they can resolve it.
For now I will close this issue.
