### ISSUE TITLE
Typechecking fails in lps2pbes after applying lpsparunfold twice

### ISSUE THREAD

**Issue by mlaveaux** [mCRL2org/mCRL2#1645]
**Steps to reproduce:**
 - Compile the latest master version (bae3caf8c5c9d73c43895ba9775b6600c4517c6b)
 - Open a terminal in the bke example directory (examples/academic/bke)
 - Run the following commands:
  ```
  mcrl22lps bke.mcrl2 temp.lps &&
  
  lpsparunfold -sKnowledge temp.lps temp1.lps &&
  lpsparunfold -s"List(Message)" -n5 temp1.lps temp2.lps &&
  
  lps2pbes -v -f secret_not_leaked.mcf temp2.lps temp.secret_not_leaked.pbes
```
**Expected result**
The linear process temp2.lps can be used to generate a PBES for verification.

**Actual result**
The following error:
```
[error]   Unknown operation @c0.
[error]   Error occurred while typechecking encrypt(nonce(0), address(A), public_key(A)) as right hand side of equation pi_S1_([])  =  encrypt(nonce(0), address(A), public_key(A)).
[error]   Failed to type check data specification.
```

**Notes**
I have not look into reducing this to a small example yet. The linear process temp1.lps can be used with lps2pbes to obtain a PBES. Furthermore, "@c0" seems to be the zero constructor of the natural numbers. After the following commands the linear process temp3.lps can also be used just fine.

```
lpspp temp2.lps temp2.txt && mcrl22lps -n temp2.txt temp3.lps
```

**Comment by jgroote** [comment]
The problem has to do with typechecking. 
When merging two specifications, which happens when a modal formula (with optionally extra data declarations) is 
merged with an lps, the types are checked again. However, the .lps has internal functions. These were checked
until the recent change in the automatically generated standard data types, in which these functions can be declared
internal, and are not allowed to be used anymore internally. This leads to problems and needs to be adapted.

**Comment by jgroote** [comment]
This problem has been resolved in the commit indicated above.

**Comment by jgroote** [comment]
And it should be closed.....

**Comment by c0** [comment]
Thanks @mlaveaux and @jgroote for fixing this, I was feeling a little empty inside.
