### ISSUE TITLE
Developer documentation is missing from mcrl2.org

### ISSUE THREAD

**Issue by tneele** [mCRL2org/mCRL2#1657]
The webpage https://mcrl2.org/web/developer_manual/developer.html used to contain the develop documentation, but right now, there are only some menus and the header "mCRL2 library documentation". Otherwise, the page is blank.

Hopefully this can be resolved so the documentation is easily accessible again.

**Comment by mlaveaux** [comment]
Commit d775157140ea0c595db7c17a94611a903a5a44cb should hopefully address this issue. There was an error message stating that the list-table could not be parsed since some rows had only one entry instead of two entries. It is now possible to generate the index page locally. I have no clue why this suddenly became an issue since the TeamCity servers have not been updated for some time. Unfortunately one of the TeamCity servers is dead so it will take some time until the mcrl2 pages are being updated again.

**Comment by mlaveaux** [comment]
The documentation is now fixed.
