### ISSUE TITLE
Empty sorts cause errors indirectly

### ISSUE THREAD

**Issue by markuzzz** [mCRL2org/mCRL2#1661]
Minimal example spec:
```
sort
	FunctionName;
	Operation = struct function(FunctionName) | add(Int);
init delta;
```
As can be seen, the sort `FunctionName` is not defined further, this code parses just fine. However, some terms can now not be rewritten. For example: `forall g:List(Operation). g == [add(1)] => #g == 1`, does not rewrite to true (even though it doesn't directly refer to `FunctionName`).

When `FunctionName` is given structs, `forall g:List(Operation). g == [add(1)] => #g == 1`, does rewrite to true.
```
sort
	FunctionName = struct F1;
	Operation = struct function(FunctionName) | add(Int);
init delta;
```
I think either an error should be given for not defining a sort, or the rewriter/enumerator should be able to deal with it.

**Comment by tneele** [comment]
With my limited knowledge of the theory behind sort definitions, I think this is not an easy problem to resolve. First of all, throwing an error for sorts that do not have a constructor will lead to problems, because the built-in sort `Real` also does not have any constructors (for the reason that there is no way to construct all irrational numbers).

So, in my view, the only real solution is to make the rewriter smarter. When it comes to quantifiers, the current approach is to feed it to the enumerator and check sufficiently many values for `g` in this case, and see whether we can derive that the expression is equivalent to true or false. However, `g` cannot be instantiated, because it requires instantiation of the sort `FunctionName`, which has no constructors.

A smarter rewriter would conclude that `g == [add(1)] => #g == 1` is equivalent to `#[add(1)] == 1`, which rewrites to true, and the problem is resolved. Issue #1300 In some sense falls in the same category.

**Comment by markuzzz** [comment]
I see, I hadn't realised there might be sorts without constructors for which there do exist values (such as reals). In my case the sort FunctionName doesn't have constructors because there doesn't exist any FunctionName (for this specific model, the mCRL2 code is generated). I fixed the issue by including a dummy function name when there aren't any functions in the model.

**Comment by jgroote** [comment]
Hello Markuzz,

Your original example

forall g:List(Operation). g == [add(1)] => #g == 1

will most likely rewrite to true when applying the one point rewriter.
This works like the sum elimination theorem, which would also eliminate it.
The rewriter once had an option to always rewrite expressions as the one
above, but it could be that the capabilities have been split over various rewriters
through time. There is a trade off  between adding more capabilites to all tools,
which makes them slower if the capabilities are not of use, or splitting capabilities
over different tools.

The default way to solve this is by enumerating all elements of g. This works when
g is enumerable, but then the sort of g must completely be constructed out of sorts
that have constructors. If a sort does not have constructors -- according to the semantics --
the number of elements of that sort is not restricted, and the sort can contain elements
not denotable by terms.

Jan Friso

------------------------------------------------------------------------------------------------------------------------
Jan Friso Groote, Eindhoven University of Technology, Department of Mathematics and
Computer Science, Metaforum room MF 6.079b, Groene Loper 5, 5612 AE Eindhoven.
The Netherlands. +31-40-247 5003, secretary: +31-40-247 5145,
***@***.******@***.***>, www.win.tue.nl/~jfg<http://www.win.tue.nl/~jfg>, Skype: janfriso
Home: Hoekstraat 56, 5674 NP Nederwetten, +31 40 2845414, +31 6 81922128


From: markuzzz ***@***.***>
Date: Friday, 3 December 2021 at 13:17
To: mCRL2org/mCRL2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [mCRL2org/mCRL2] Empty sorts cause errors indirectly (Issue #1661)

I see, I hadn't realised there might be sorts without constructors for which there do exist values (such as reals). In my case the sort FunctionName doesn't have constructors because there doesn't exist any FunctionName (for this specific model, the mCRL2 code is generated). I fixed the issue by including a dummy function name when there aren't any functions in the model.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FmCRL2org%2FmCRL2%2Fissues%2F1661%23issuecomment-985473215&data=04%7C01%7C%7Cbcf0ca1f3bff474a0adf08d9b656e82e%7Ccc7df24760ce4a0f9d75704cf60efc64%7C1%7C0%7C637741306651589039%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lINJRzseUuhehZ1RbtqvAuk6pjwo%2BNsNTrCfRhfr1mI%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACE5HUFYZ3Z24RJOIOIVPQLUPCYOLANCNFSM5JJNEHZQ&data=04%7C01%7C%7Cbcf0ca1f3bff474a0adf08d9b656e82e%7Ccc7df24760ce4a0f9d75704cf60efc64%7C1%7C0%7C637741306651598995%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=IoufHLv81uVLrpeSx71w%2Bq838TUGI3Hui1Y1gOdkRt8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cbcf0ca1f3bff474a0adf08d9b656e82e%7Ccc7df24760ce4a0f9d75704cf60efc64%7C1%7C0%7C637741306651598995%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2r7wPDozvoE85xai0Nv732KWHypEUIF%2BpjoTkJjmRJ8%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cbcf0ca1f3bff474a0adf08d9b656e82e%7Ccc7df24760ce4a0f9d75704cf60efc64%7C1%7C0%7C637741306651608950%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XJii0fUMimqv0XTEdJcr7M5yfM6SickfFuBVncDoDYk%3D&reserved=0>.

**Comment by markuzzz** [comment]
Thanks for the explanation Thomas and Jan Friso. For me it is fine if the issue is closed. I will leave it open in case you want to leave it open for future reference.
