### ISSUE TITLE
ltsreduce -ebisim does not remove duplicates of transitions. 

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1666]
Consider the lts test.aut

des (0,2,1)
(0,"a",0)
(0,"a",0)

Applying ltsconvert -ebisim test.aut testr.aut yields

des (0,2,1)
(0,"a",0)
(0,"a",0)

All other variants, bisim-gv, bisim-sig and bisim-gjkw do remove the double transition.

I would expect that the new bisimulation reduction algorithm should do the same.

**Comment by dnjansen** [comment]
To keep the running time strictly within _O_(_m_ log _n_), no operations are permitted on blocks with only one state (as log 1 = 0).  This is a fundamental choice; I will check whether this constraint can be ignored if the whole LTS has only one state, possibly with a warning along the lines ``Reducing a block with a single state, the O(m log n) time bound cannot be guaranteed.``

**Comment by dnjansen** [comment]
These two commits should correct the bug and issue the promised warning.

Unfortunately, for strong bisimulation using the _dnj algorithms, warnings about duplicated transitions are printed, but for branching bisimulation no such warnings are given, because in the latter case, duplicated transitions are silently removed by scc_reduce().  This function mainly removes τ loops but also has to simplify transitions that become duplicated by identifying states on a τ loop.  Without additional computation it is difficult to distinguish such legitimately generated duplicates from duplicates that already were present in the original LTS.
