### ISSUE TITLE
Use after free while rewriting expression with quantifiers

### ISSUE THREAD

**Issue by tneele** [mCRL2org/mCRL2#1676]
There is a use-after-free problem in the data rewriter that occurs when rewriting an expression with quantifiers. This problem was found by the address sanitizer. The problem can be reproduced by turning on the cmake option `MCRL2_ENABLE_ADDRESSSANITIZER` and running `mcrl2i` in the following manner:
```
$ ASAN_OPTIONS=detect_odr_violation=0:malloc_context_size=150 stage/bin/mcrl2i
mCRL2 interpreter (type h for help)
? e (forall m1: Nat. exists m2: Nat. m2 > 2 + m1)
```
A complete trace produced by the sanitizer is attached: [asan.txt](https://github.com/mCRL2org/mCRL2/files/8583250/asan.txt)

**Comment by jgroote** [comment]
This problem is caused as in libraries/atermpp/include/mcrl2/atermpp/detail/aterm_pool_implementation.h an aterm_int is sweeped before other terms, especially terms with three arguments. In on_delete_variable a variable of the shape variable("name",sort,index) where index is an aterm_int is inspected, before it is remove. However at that point the index is already removed. This is repaired by changing the order in which terms are swept. An aterm_int is now swept later than an aterm with more parameters.

**Comment by jgroote** [comment]
This issue is now resolved.
