### ISSUE TITLE
Webpage for lpsreach manual needs to be written

### ISSUE THREAD

**Issue by matifch** [mCRL2org/mCRL2#1683]
lpsreach -h shows a url, i.e., "http://www.mcrl2.org/web/user_manual/tools/release/lpsreach.html"
but the required webpage is not available at the moment.

**Comment by tneele** [comment]
`lpsreach` is a developer tool, and thus does not have a webpage. Webpages are automatically generated for release and experimental tools. One could argue that this URL should not be shown for developer tools, but I think it's a rather minor issue, since developer tools are included in release or nightly packages. If it turns out that `lpsreach` has wider application potential than just for tool development, we might consider making it an experimental tool. I will leave that up to @mlaveaux.

**Comment by mlaveaux** [comment]
The tools lpsreach (and pbessolvesymbolic) have been moved into experimental and when the website updates will have corresponding documentation.
