### ISSUE TITLE
Lps2lts creates output file before LTS is fully explored

### ISSUE THREAD

**Issue by Valo13** [mCRL2org/mCRL2#1694]
When `lps2lts` is executed, it already creates an output lts file when it starts the exploration, which then grows during exploration. This seems to be inconsistent with other tools. For instance, mcrl22lps and lps2pbes seem to only output the lps respectively pbes when they have been fully created. Is this intentional?

I'm asking this because it currently results in an issue in `mcrl2ide`, where if `lps2lts` is aborted and then run again, `mcrl2ide` thinks that the LTS was already created because it sees the incomplete LTS file and tries to open it in `ltsgraph` (which fails). I think I could fix this on the `mcrl2ide` side by deleting the LTS file when the process is aborted, but since it is the only tool for which this occurs, I was wondering whether this was intentional behaviour of `lps2lts`.

**Comment by jgroote** [comment]
It is intended to already start writing an .lts or .aut file while exploring. This allows
to save the transitions to disk without having to store them in memory. This has a substantial
impact on the amount of memory that is required. There is an option to postpone writing
the transitions to disk, but using that is not recommended.

It is not really intended that other tools happen to write their results at the end. It just happens
to be the case, but could have been otherwise.

Jan Friso

------------------------------------------------------------------------------------------------------------------------
Jan Friso Groote, Eindhoven University of Technology, Department of Mathematics and
Computer Science, Metaforum room MF 6.079b, Groene Loper 5, 5612 AE Eindhoven.
The Netherlands. +31-40-247 5003, secretary: +31-40-247 5145,
***@***.******@***.***>, www.win.tue.nl/~jfg<http://www.win.tue.nl/~jfg>, Skype: janfriso
Home: Hoekstraat 56, 5674 NP Nederwetten, +31 40 2845414, +31 6 81922128


From: Olav Bunte ***@***.***>
Date: Friday, 19 August 2022 at 11:29
To: mCRL2org/mCRL2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mCRL2org/mCRL2] Lps2lts creates output file before LTS is fully explored (Issue #1694)

When lps2lts is executed, it already creates an output lts file when it starts the exploration, which then grows during exploration. This seems to be inconsistent with other tools. For instance, mcrl22lps and lps2pbes seem to only output the lps respectively pbes when they have been fully created. Is this intentional?

I'm asking this because it currently results in an issue in mcrl2ide, where if lps2lts is aborted and then run again, mcrl2ide thinks that the LTS was already created because it sees the incomplete LTS file and tries to open it in ltsgraph (which fails). I think I could fix this on the mcrl2ide side by deleting the LTS file when the process is aborted, but since it is the only tool for which this occurs, I was wondering whether this was intentional behaviour of lps2lts.

**Comment by Valo13** [comment]
Ok, the issue needs to be fixed in `mcrl2ide` then.
