### ISSUE TITLE
Assertion failure in parallel exploration of 1394-fin

### ISSUE THREAD

**Issue by mlaveaux** [mCRL2org/mCRL2#1695]
Running the command ```lps2lts --threads=8 -v ./benchmarks/1394-fin.lps``` (after enabling and building the benchmarks target) on a build with assertions enabled can yield the following assertion failure after some time:

> lps2lts: /home/mlaveaux/mCRL2/libraries/utilities/include/mcrl2/utilities/detail/indexed_set.h:98: void mcrl2::utilities::indexed_set<atermpp::term_balanced_tree<mcrl2::data::data_expression>, std::hash<atermpp::term_balanced_tree<mcrl2::data::data_expression> >, std::equal_to<atermpp::term_balanced_tree<mcrl2::data::data_expression> >, std::allocator<atermpp::term_balanced_tree<mcrl2::data::data_expression> >, true, atermpp::deque<atermpp::term_balanced_tree<mcrl2::data::data_expression>, std::allocator<atermpp::detail::reference_aterm<atermpp::term_balanced_tree<mcrl2::data::data_expression>, void> > > >::unlock_shared(std::size_t) const [Key = atermpp::term_balanced_tree<mcrl2::data::data_expression>, Hash = std::hash<atermpp::term_balanced_tree<mcrl2::data::data_expression> >, Equals = std::equal_to<atermpp::term_balanced_tree<mcrl2::data::data_expression> >, Allocator = std::allocator<atermpp::term_balanced_tree<mcrl2::data::data_expression> >, ThreadSafe = true, KeyTable = atermpp::deque<atermpp::term_balanced_tree<mcrl2::data::data_expression>, std::allocator<atermpp::detail::reference_aterm<atermpp::term_balanced_tree<mcrl2::data::data_expression>, void> > >]: Assertion `m_thread_control[thread_index].busy_flag' failed.

The issue occurs in commit (b894451b23aae11205e9cfc73699aca1c2bc714f), but also already occurs before I changed anything about the protections of container objects (d47e848151b3744a163e899e9a34bc8003fcbf5b).

**Comment by jgroote** [comment]
This problem occurs because at certain moments, when accessing an indexed set, a thread forgets is thread_index, and defaults to thread 0. Then several threads are using the busy-forbidden flags for thread 0, which apparently led to little trouble in the parallel implementation, but was correctly observed by asserts.

The thread administration is mended where needed. Moreover, for safety purposes, when using multi-threading the default thread_index 0 is not used anymore. This thread_index will be reserved for sequential processes.

**Comment by jgroote** [comment]
The commit referenced to above resolves this issue.

**Comment by jgroote** [comment]
And hence close...
