### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [mCRL2org/mCRL2#1767]
Would you like to wrap any pointers with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [MaxMeasureLiftingStrategy2](https://github.com/mCRL2org/mCRL2/blob/964278dad1f572799af66d950060c7d7244cfd30/libraries/pg/source/MaxMeasureLiftingStrategy.cpp#L14-L31)
- [PredecessorLiftingStrategy](https://github.com/mCRL2org/mCRL2/blob/964278dad1f572799af66d950060c7d7244cfd30/libraries/pg/source/PredecessorLiftingStrategy.cpp#L12-L49)
- [thread_aterm_pool](https://github.com/mCRL2org/mCRL2/blob/964278dad1f572799af66d950060c7d7244cfd30/libraries/atermpp/include/mcrl2/atermpp/detail/thread_aterm_pool.h#L30-L56)

**Comment by mlaveaux** [comment]
I have replaced the occurrences of owning raw pointers in PredecessorLiftingStrategy and MaxMeasuireLiftingStrategy2. The occurrence in thread_aterm_pool can unfortunately not be replaced by a unique_ptr, because we need to ensure that the variable hashtable remains valid during the exit handler since the destruction order is undefined. A unique ptr can be released, but then the pointer in the global aterm pool is no longer valid.

**Comment by elfring** [comment]
:thought_balloon: Would you become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/owning-memory.html "Checking handling of pointers")?

**Comment by mlaveaux** [comment]
We ran clang-tidy and fixed several suggestions. Unfortunately, some of the legacy code makes this difficult, because it triggers so many suggestions.
